# Generated by Django 5.1.2 on 2024-10-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_author_created_at_quote_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='description',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
